name: Analyze PowerShell Script

on: [push, pull_request]

jobs:
  script_analyzer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run PSScriptAnalyzer
      run: |
        Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
        $results = Invoke-ScriptAnalyzer -Path store-container-manager.ps1 -Settings PSScriptAnalyzerSettings.psd1
        $results | ConvertTo-Csv | Out-File analysis-results-2.csv 
      shell: pwsh

    - name: setup python
      uses: actions/setup-python@v5
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x'

    - name: run python script
      run: |
        python convert_results.py

    - name: Install sonar cli 5.0 and push external package to Sonar server in azure
      run: |
        wget -O sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.0.2966-linux.zip?_gl=1*19xt29g*_gcl_au*MTE5MTE3MDIxOC4xNzIxMTgwMzA5*_ga*MTQzODIxODQwMi4xNzIxMTgwMzA5*_ga_9JZ0GZ5TC6*MTcyMzY0OTkwNC4xNC4xLjE3MjM2NTAyODcuNjAuMC4w
        unzip sonar-scanner-cli.zip -d $HOME
        echo "$HOME/sonar-scanner-5.0.0.2966-linux/bin" >> $GITHUB_PATH

    - name: run sonnar-scaner
      run: |
        sonar-scanner \
          -Dsonar.projectKey=powershell \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://20.81.187.233:9000 \
          -Dsonar.login=sqp_13bc0363190429f734aed26be227d32fa8665a7a \
          -Dsonar.sarifReportPaths=result.sarif \
          -Dsonar.exclusions=convert_results.py
